name: build
on:
  push:
  tags:
      - 'r*.*'
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Releasesupload
        uses: softprops/action-gh-release@v1
        with:
          files: Release.txt
      - name: Cleantags
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
        delete_release: true
        tag_name: r29.0
                